// src/layouts/app/components/sidebar/sidebarNavConfig.js

import {
  LayoutDashboard,
  Building2,
  Users,
  Package,
  ShoppingCart,
  DollarSign,
  Settings,
  HelpCircle,
  Boxes,
  Database,
  Layers,
  Sparkles,
  FlaskConical,
  Ruler,
  FileSpreadsheet,
  Receipt,
  Truck,
  Store,
  PieChart,
  Landmark,
  Wallet,
  ArrowLeftRight,
  QrCode,
  FileCheck2,
  Banknote,
  BookOpen,
  CalendarDays,
  FileText,
  BarChart3,
  GitBranch,
  ShieldAlert,
  ShieldCheck,
  Contact,
  Clock,
  FileUp,
  RefreshCw,
  FolderTree,
} from "lucide-react";

import { ROUTES } from "@/constants";

// Permission keys match the exact backend PERMISSIONS constant:
//   company:view, branch:view, workspace-member:view, role:view
//   customer:view, supplier:view
//   product:view, global-product:view, category:view, hsn:view, manufacturer:view, salt:view, uom:view, product-form:view, bank-master:view
//   pos:view, bill:view, purchase:view, sale:view, marketplace-store:view, marketplace-product:view
//   account:view, account-group:view, account-balance:view, journal-voucher:view, ledger:view, report:view, financial-period:view
//   bank-account:view, cash-account:view, fund-transfer:view, cheque:view, payment-qr:view, cash-denomination:view, bank-deposit-slip:view
//
// Items WITHOUT a permission/permissions key are always visible to all authenticated users.

export const SIDEBAR_NAV_GROUPS = [
  {
    id: "overview",
    label: "Home",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: ROUTES.DASHBOARD,
        icon: LayoutDashboard,
      },
      {
        id: "setup-center",
        label: "Setup Center",
        path: ROUTES.SETUP_CENTER,
        icon: Sparkles,
        requireOwner: true,
      },
    ],
  },
  {
    id: "daily-ops",
    label: "Daily Ops",
    items: [
      {
        id: "billing",
        label: "Billing (POS)",
        path: ROUTES.SALES,
        icon: ShoppingCart,
        permissions: ["pos:view", "bill:view", "sale:view"],
        keywords: ["pos", "billing", "sales", "invoice", "counter"],
      },
      {
        id: "sale-invoices",
        label: "Sale Invoices",
        path: ROUTES.BILLING,
        icon: Receipt,
        permissions: ["bill:view", "sale:view"],
        keywords: ["sale invoices", "sales", "invoices", "bills", "sales register"],
      },
      {
        id: "purchases",
        label: "Purchases",
        path: ROUTES.PURCHASES,
        icon: Truck,
        permission: "purchase:view",
        keywords: ["purchases", "vendor bills", "purchase order"],
      },
      {
        id: "pharmacy-stock",
        label: "Pharmacy Stock",
        path: ROUTES.WORKSPACE_PRODUCTS,
        icon: Boxes,
        permission: "product:view",
        keywords: ["stock", "inventory", "medicines", "products"],
      },
      {
        id: "transfer-orders",
        label: "Transfer Orders",
        path: "/inventory/transfer-orders",
        icon: ArrowLeftRight,
        keywords: ["transfer orders", "stock transfer", "inventory transfer", "to"],
      },
      {
        id: "customers",
        label: "Customers",
        path: ROUTES.CUSTOMERS,
        icon: Users,
        permission: "customer:view",
        keywords: ["customers", "parties", "debtors"],
      },
      {
        id: "suppliers",
        label: "Suppliers",
        path: ROUTES.SUPPLIERS,
        icon: Truck,
        permission: "supplier:view",
        keywords: ["suppliers", "vendors", "creditors"],
      },
      {
        id: "business-days",
        label: "Business Days",
        path: "/operations/business-days",
        icon: CalendarDays,
      },
      {
        id: "shifts",
        label: "Shifts",
        path: "/operations/shifts",
        icon: Clock,
      },
    ],
  },
  {
    id: "money",
    label: "Money & Treasury",
    items: [
      {
        id: "cash-counter",
        label: "Cash Counter",
        path: ROUTES.BRANCH_CASH,
        icon: Wallet,
        permission: "cash-account:view",
        keywords: ["cash counter", "branch cash", "till"],
      },
      {
        id: "bank-accounts",
        label: "Bank Accounts",
        path: ROUTES.BANK_ACCOUNTS,
        icon: Landmark,
        permission: "bank-account:view",
        keywords: ["bank accounts", "banks list", "bank list", "banks"],
      },
      {
        id: "bank-deposit-slips",
        label: "Bank Deposit Slips",
        path: ROUTES.BANK_DEPOSIT_SLIPS,
        icon: FileUp,
        permission: "bank-deposit-slip:view",
        keywords: ["bank slip", "deposit slip", "cash in transit", "bank deposit", "slips"],
      },
      {
        id: "payment-qrs",
        label: "UPI / QR",
        path: ROUTES.PAYMENT_QRS,
        icon: QrCode,
        permission: "payment-qr:view",
        keywords: ["upi", "qr code", "payment qr"],
      },
      {
        id: "more-treasury",
        label: "More Treasury & Logs",
        icon: Receipt,
        permissions: [
          "bank-transaction:view",
          "cash-transaction:view",
          "fund-transfer:view",
          "cheque:view",
          "cash-denomination:view",
          "cash-exchange:view",
        ],
        children: [
          {
            id: "bank-transactions",
            label: "Bank Transactions",
            path: ROUTES.BANK_TRANSACTIONS,
            icon: Landmark,
            permission: "bank-transaction:view",
            keywords: ["bank transactions", "bank statement", "banking"],
          },
          {
            id: "cash-transactions",
            label: "Cash Transactions",
            path: ROUTES.CASH_TRANSACTIONS,
            icon: Banknote,
            permission: "cash-transaction:view",
            keywords: ["cash transactions", "cash log", "cash statement"],
          },
          {
            id: "transfers",
            label: "Transfers",
            path: ROUTES.FUND_TRANSFERS,
            icon: ArrowLeftRight,
            permission: "fund-transfer:view",
            keywords: ["transfers", "fund transfer", "internal transfer"],
          },
          {
            id: "cheques",
            label: "Cheques",
            path: ROUTES.CHEQUES,
            icon: FileCheck2,
            permission: "cheque:view",
            keywords: ["cheques", "cheque management", "checks"],
          },
          {
            id: "cash-denominations",
            label: "Cash Denominations",
            path: ROUTES.CASH_DENOMINATIONS,
            icon: Banknote,
            permission: "cash-denomination:view",
            keywords: ["cash tally", "cash denominations", "note count"],
          },
          {
            id: "cash-exchanges",
            label: "Cash Exchanges",
            path: ROUTES.CASH_EXCHANGES,
            icon: RefreshCw,
            permission: "cash-exchange:view",
            keywords: ["cash exchange", "petty cash exchange"],
          },
        ],
      },
    ],
  },
  {
    id: "finance",
    label: "Finance & Accounting",
    items: [
      {
        id: "accounts",
        label: "Accounts",
        path: ROUTES.ACCOUNTS,
        icon: Layers,
        permission: "account:view",
        keywords: ["accounts", "chart of accounts", "coa", "account list", "ledger accounts"],
      },
      {
        id: "ledger",
        label: "General Ledger",
        path: ROUTES.LEDGER,
        icon: BookOpen,
        permission: "ledger:view",
        keywords: ["general ledger", "ledger", "account statement", "statement"],
      },
      {
        id: "account-balances",
        label: "Account Balances",
        path: ROUTES.ACCOUNT_BALANCES,
        icon: Landmark,
        permission: "account-balance:view",
        keywords: ["account balances", "balances", "trial balance"],
      },
      {
        id: "vouchers",
        label: "Manual Adjustments",
        path: ROUTES.JOURNAL_VOUCHERS,
        icon: FileText,
        permission: "journal-voucher:view",
        keywords: ["manual adjustments", "journal vouchers", "vouchers", "jv"],
      },
      {
        id: "more-finance",
        label: "More Finance & Reports",
        icon: FolderTree,
        permissions: [
          "account:view",
          "account-group:view",
          "report:view",
          "financial-period:view",
          "ledger:view",
        ],
        children: [
          {
            id: "account-groups",
            label: "Account Groups",
            path: ROUTES.ACCOUNT_GROUPS,
            icon: Boxes,
            permission: "account-group:view",
            keywords: ["account groups", "groups"],
          },
          {
            id: "gst-ledger",
            label: "GST Reports",
            icon: FileCheck2,
            permissions: ["ledger:view"],
            children: [
              {
                id: "gstr-1",
                label: "GSTR-1",
                path: ROUTES.GSTR1,
                icon: FileText,
                permission: "ledger:view",
                keywords: ["gstr1", "gstr-1", "sales tax"],
              },
              {
                id: "gstr-2",
                label: "GSTR-2",
                path: ROUTES.GSTR2,
                icon: FileText,
                permission: "ledger:view",
                keywords: ["gstr2", "gstr-2", "purchase tax"],
              },
            ],
          },
          {
            id: "reports",
            label: "Financial Reports",
            path: ROUTES.REPORTS,
            icon: BarChart3,
            permission: "report:view",
            keywords: ["financial reports", "reports", "profit loss", "balance sheet"],
          },
          {
            id: "periods",
            label: "Financial Periods",
            path: ROUTES.FINANCIAL_PERIODS,
            icon: CalendarDays,
            permission: "financial-period:view",
            keywords: ["financial periods", "fiscal year", "periods"],
          },
        ],
      },
    ],
  },
  {
    id: "manage",
    label: "Manage",
    items: [
      {
        id: "organization",
        label: "Organization",
        icon: Building2,
        permissions: [
          "company:view",
          "branch:view",
          "workspace-member:view",
          "role:view",
        ],
        children: [
          {
            id: "companies",
            label: "Companies",
            path: ROUTES.COMPANIES,
            icon: Building2,
            permission: "company:view",
          },
          {
            id: "branches",
            label: "Branches",
            path: ROUTES.BRANCHES,
            icon: GitBranch,
            permission: "branch:view",
          },
          {
            id: "members",
            label: "Staff & Members",
            path: ROUTES.WORKSPACE_MEMBERS,
            icon: Users,
            permission: "workspace-member:view",
          },
          {
            id: "roles-permissions",
            label: "Roles & Permissions",
            path: ROUTES.ROLES,
            icon: ShieldCheck,
            permission: "role:view",
          },
        ],
      },
    ],
  },
  {
    id: "account",
    label: "Account",
    items: [
      {
        id: "help",
        label: "Help & Support",
        path: ROUTES.HELP_CENTER,
        icon: HelpCircle,
      },
    ],
  },
];
