// src/features/setup/constants/recommendedSteps.js
// Recommended optional steps to display at the bottom of the Setup Center page after company & branch are complete.

import { ROUTES } from "@/constants";

export const recommendedSteps = [
  {
    id: "products",
    title: "Add Products & Medicines",
    category: "INVENTORY & CATALOG",
    description: "Add medicines, salt compositions, barcodes, HSN codes, and opening stock to your pharmacy catalog.",
    route: ROUTES.CREATE_WORKSPACE_PRODUCT || "/workspace-products/create",
    badge: "High Priority",
    badgeVariant: "primary",
    colorVariant: "primary",
    estimatedTime: "3 mins",
    actionText: "Add Medicine",
    iconName: "Package",
  },
  {
    id: "suppliers",
    title: "Add Suppliers & Vendors",
    category: "PROCUREMENT",
    description: "Register pharmaceutical wholesale distributors, drug license details, and payment credit terms.",
    route: ROUTES.SUPPLIERS,
    badge: "Recommended",
    badgeVariant: "info",
    colorVariant: "info",
    estimatedTime: "2 mins",
    actionText: "Add Supplier",
    iconName: "Truck",
  },
  {
    id: "team",
    title: "Invite Staff & Pharmacists",
    category: "ACCESS & ROLES",
    description: "Invite your pharmacy staff, assign POS cashier or branch manager roles, and configure access permissions.",
    route: ROUTES.INVITE_WORKSPACE_MEMBER || "/members/invite",
    badge: "Optional",
    badgeVariant: "success",
    colorVariant: "success",
    estimatedTime: "2 mins",
    actionText: "Invite Staff",
    iconName: "UserPlus",
  },
  {
    id: "purchase",
    title: "Record First Purchase",
    category: "STOCK INWARD",
    description: "Enter supplier purchase invoices with batch numbers, expiry dates, purchase rates, and GST tax splits.",
    route: "/purchases/create",
    badge: "Operations",
    badgeVariant: "warning",
    colorVariant: "warning",
    estimatedTime: "3 mins",
    actionText: "New Purchase",
    iconName: "ShoppingCart",
  },
  {
    id: "payment-qr",
    title: "Setup UPI & Payment QR",
    category: "PAYMENTS",
    description: "Configure dynamic UPI QR codes on invoices for instant counter payments via GPay, PhonePe, and Paytm.",
    route: ROUTES.PAYMENT_QRS || "/finance/treasury/payment-qr",
    badge: "Fast Billing",
    badgeVariant: "primary",
    colorVariant: "primary",
    estimatedTime: "2 mins",
    actionText: "Configure QR",
    iconName: "QrCode",
  },
  {
    id: "pos-billing",
    title: "Launch POS Billing Counter",
    category: "SALES TERMINAL",
    description: "Test barcode billing, customer prescription lookup, fast discounts, and thermal receipt printing.",
    route: ROUTES.SALES || "/sales",
    badge: "Ready to Use",
    badgeVariant: "success",
    colorVariant: "success",
    estimatedTime: "Instant",
    actionText: "Open POS",
    iconName: "Receipt",
  },
];

export default recommendedSteps;
